### ISSUE TITLE
Adding message with initialInvisibilitySeconds has no effect. 

### ISSUE THREAD

**Issue by marekasf** [paradoxical-io/cassieq#122]
"initialInvisibilitySeconds" parameter in addMessage(...) has no effect.
See the test below:

```
        final QueueName queueName = QueueName.valueOf(QUEUE_NAME);
        final AccountName accountName = AccountName.valueOf(ACCOUNT_NAME);
        final AccountKey accountKey = AccountKey.valueOf(KEY);
        final CassieqApi client = CassieqApi.createClient("http://192.168.99.100:8080/", CassieqCredentials.key(accountName,
                accountKey));

        client.createQueue(accountName, new QueueCreateOptions(queueName)).execute();

        client.addMessage(accountName, queueName, "0").execute();
        client.addMessage(accountName, queueName, "4", 400000l).execute();
        client.addMessage(accountName, queueName, "3", 300000l).execute();
        client.addMessage(accountName, queueName, "2", 200000l).execute();
        client.addMessage(accountName, queueName, "1").execute();

        int counter = 0;

        for (int i = 0; i < 5; ++i)
        {
            final GetMessageResponse body = client.getMessage(accountName, queueName, 10000l).execute().body();
            counter += body == null ? 0 : 1;

        }

        client.deleteQueue(accountName, queueName).execute();
        // counter should be 2 but is always 5
        // it means we consumed messages with visibility in >= 200000 seconds (55 hours)
        System.out.println(" COUNTER : " + counter);

        assert counter <= 2;
```

**Comment by devshorts** [comment]
Great catch! I'll have a fix out soon. The issue here isn't so much any cassieq internals error, its a client error where our query param in the api was:

```
initialInvisibilityTime
```

But the client was sending

```
initialInvisibilitySeconds
```

So the initial invis was always set to 0 when using the java client.  I'd like to make this breaking API change because its much more descriptive. @jakeswenson @tronroy thoughts?  we _could_ make it backwards compatbile, but given cq is still in beta I think we should do the right thing.

**Comment by tbconroy** [comment]
That api change sounds good to me. I agree with your thoughts on backwards compatibility.

**Comment by jakeswenson** [comment]
@devshorts @tronroy agree, lets make it backwards compatible and publish a deprecation period. 2 versions sound good?

**Comment by devshorts** [comment]
@tronroy I left the original query param but exposed `initialInvisibilitySeconds` which should be used instead now.  Can you update the ruby client to reflect that? The deprecated query param wont' show up in swagger, but it will be accepted if its sent in

**Comment by tbconroy** [comment]
Yeah, no problem.
