### ISSUE TITLE
Add stats

### ISSUE THREAD

**Issue by devshorts** [paradoxical-io/cassieq#17]
We should add a stats api
- Estimated queue size (monoton - read pointer)
- Estimated read rate
- Estimated ack rate
- Estimated publish rate
- Repair worker republish rate

We can leverage dropwizard metrics to capture/expose all of this

**Comment by jakeswenson** [comment]
Some are simpler than others, we can get rates/per node easily with drop wizard metrics, and Queue size. these are trivial.

For that more complicated full aggregates we should create a table to buckitize by some configurable time window, and have each node dump a counter/value into that bucket. then we can process a bucket.

**Comment by jakeswenson** [comment]
Also.... this is where a sick service like track it could be cool.... but maybe graphite could do it too...

**Comment by jakeswenson** [comment]
Counter columns seem relevant: https://docs.datastax.com/en/cql/3.0/cql/cql_using/use_counter_t.html

**Comment by jakeswenson** [comment]
https://docs.datastax.com/en/cql/3.3/cql/cql_using/useCountersConcept.html
