### ISSUE TITLE
Repair worker poll for new queues

### ISSUE THREAD

**Issue by devshorts** [paradoxical-io/cassieq#2]

**Comment by jakeswenson** [comment]
This is half fixed, need this for better farm support

**Comment by devshorts** [comment]
To be specific, we need to notify or poll repair workers when a queue is added on a machine that the repair worker isn't on. Currenlty we only support spinning up a worker on the machine that created the queue.

Workers, on start, pull all queues right now which also isn't the best thing for scaleablitiy

**Comment by jakeswenson** [comment]
Moving out to RC3 because we have something working for RC2
