### ISSUE TITLE
Create single instance non persisted "experiment" mode

### ISSUE THREAD

**Issue by devshorts** [paradoxical-io/cassieq#66]
To encourage experimentation and discovery, we should expose a way to run the container in auth'd non-persisted single instance mode.

We could use an in memory cassandra and disable all auth in this mode so that people can just create queues, toy around, see if they like the api/use cases etc.

When the container is restarted all data is lost, so its transient.

**Comment by jakeswenson** [comment]
> and disable all auth

Assuming you mean not to require auth. Someone should still be able to make credentials and test them, but if they're not there its assumed `AuthorizationLevel.All`

that way someone could still play with auth.

**Comment by devshorts** [comment]
+1 good clarification, I hadn't though to that.

What we could do is seed a new account and in the console spit out the key so people can use that in the swagger definitions.  Any other accounts they want to make on top of that are all on them

**Comment by jakeswenson** [comment]
@devshorts will be finishing
