### ISSUE TITLE
Support a micro-container option

### ISSUE THREAD

**Issue by jakeswenson** [paradoxical-io/cassieq#67]
It'd be nice to base our image on the lightweight [alpine linux container](https://hub.docker.com/_/alpine/) image as a base. Lets look into what it's like to build a container with java so we can run caseiq.

**Comment by jakeswenson** [comment]
https://www.brianchristner.io/docker-is-moving-to-alpine-linux/

**Comment by jakeswenson** [comment]
lets add a cool badge too
https://imagelayers.io/?images=alpine:latest

**Comment by jakeswenson** [comment]
[![](https://badge.imagelayers.io/paradoxical/cassieq:latest.svg)](https://imagelayers.io/?images=paradoxical/cassieq:latest)

**Comment by devshorts** [comment]
:pig:
