### ISSUE TITLE
Create ruby based client

### ISSUE THREAD

**Issue by devshorts** [paradoxical-io/cassieq#89]
It would be awesome to have a client for python users that can be installed via gem.  It would have to handle the basic API (not admin api, though I think that should be a separate package), and it should be able to properly generate signature based headers, key based headers, and append query based url params.

Related to #88

**Comment by jakeswenson** [comment]
@tronroy is looking at this i think. Please comment here if thats the case

**Comment by tbconroy** [comment]
Started working on this. Here's the repo:
https://github.com/tronroy/cassieq_client

**Comment by devshorts** [comment]
Awesome! Thanks tom!
